// src/components/works/WorkList.tsx
'use client';

import { useState, useRef } from 'react';

import WorkCard from './WorkCard';
import CategoryButtons from './CategoryButtons';
import { useIntersectionObserver } from '../../hooks/useIntersectionObserver';
import type { Work } from '../../types/work';

interface WorkListProps {
  initialTags: string[];
  initialWorks: Work[];
}

interface WorkItemProps {
  work: Work;
  index: number;
}

function WorkItem({ work, index }: WorkItemProps) {
  const ref = useRef<HTMLDivElement | null>(null);
  const [isVisible, setIsVisible] = useState(false);

  useIntersectionObserver({
    target: ref,
    onIntersect: (entry) => {
      if (entry.isIntersecting) {
        setIsVisible(true);
      }
    },
    threshold: 0.1,
    rootMargin: '0px 0px 40% 0px',
  });

  return (
    <div
      ref={ref}
      className="transform transition-all duration-1500"
      style={{
        transitionDelay: `${index * 75}ms`,
        transitionTimingFunction: 'cubic-bezier(.1,1,.3,1)',
        filter: isVisible ? 'blur(0px)' : 'blur(4px)',
        opacity: isVisible ? 1 : 0,
        transform: isVisible ? 'translateY(0)' : 'translateY(30px)',
      }}
    >
      <WorkCard work={work} />
    </div>
  );
}

export default function WorkList({ initialTags, initialWorks }: WorkListProps) {
  const [selectedTag, setSelectedTag] = useState<string | null>(null);

  const filteredWorks: Work[] = selectedTag
    ? initialWorks.filter((work: Work) =>
        work.data.tags?.some((tag: string) => tag === selectedTag),
      )
    : initialWorks;

  return (
    <div className="flex w-full flex-col gap-8">
      {/* モバイル・タブレット用：上部にカテゴリボタン */}
      <div className="lg:hidden">
        <CategoryButtons
          tags={initialTags}
          selectedTag={selectedTag}
          onSelectTag={setSelectedTag}
        />
      </div>

      <div className="flex flex-col justify-between gap-16 lg:flex-row">
        <div className="flex-1">
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
            {filteredWorks.map((work, index) => (
              <WorkItem
                key={`${selectedTag || 'all'}-${work.id || index}`}
                work={work}
                index={index}
              />
            ))}
          </div>
        </div>

        {/* デスクトップ用：右側にカテゴリボタン */}
        <div className="hidden lg:block lg:w-32">
          <div className="lg:sticky lg:top-40 lg:ml-auto">
            <CategoryButtons
              tags={initialTags}
              selectedTag={selectedTag}
              onSelectTag={setSelectedTag}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/works/WorkList.svelte
<script lang="ts">
  import WorkItem from './WorkItem.svelte';
  import CategoryButtons from './CategoryButtons.svelte';
  import type { Work } from '../../types/work';

  interface Props {
    initialTags: string[];
    initialWorks: Work[];
  }

  let { initialTags, initialWorks }: Props = $props();

  let selectedTag: string | null = $state(null);

  const filteredWorks = $derived(
    selectedTag
      ? initialWorks.filter((work) =>
          work.data.tags?.some((tag) => tag === selectedTag),
        )
      : initialWorks,
  );

  const handleSelectTag = (tag: string | null) => {
    selectedTag = tag;
  };
</script>

<div class="flex w-full flex-col gap-8">
  <!-- モバイル・タブレット用：上部にカテゴリボタン -->
  <div class="lg:hidden">
    <CategoryButtons
      tags={initialTags}
      {selectedTag}
      onSelectTag={handleSelectTag}
    />
  </div>

  <div class="flex flex-col justify-between gap-16 lg:flex-row">
    <div class="flex-1">
      <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
        {#each filteredWorks as work, index (selectedTag + '-' + (work.id || index))}
          <WorkItem {work} {index} />
        {/each}
      </div>
    </div>

    <!-- デスクトップ用：右側にカテゴリボタン -->
    <div class="hidden lg:block lg:w-32">
      <div class="lg:sticky lg:top-40 lg:ml-auto">
        <CategoryButtons
          tags={initialTags}
          {selectedTag}
          onSelectTag={handleSelectTag}
        />
      </div>
    </div>
  </div>
</div>
